<?php 
	$productType=$_product->getTypeID();
	$product=Mage::getModel('catalog/product')->load($_product->getId());
	$eventStart = $product->getEventstartdate();
	
	$eventName = $this->stripTags($_product->getName(), null, true);

if($productType == 'event') {

	$opponent=$product->getOpponent();
	$awaystat="";
	if($opponent != ''){
		if($product->getAwaygame() != 1){
			echo "<h4 class='event verse'><a href='".$_product->getProductUrl()."' title='".$eventName."'>WSU -V- $opponent</a></h4>";
		}else{
			$awaystat="away";
			echo "<h4 class='event verse away'><a href='".$_product->getProductUrl()."' title='".$eventName."'>$opponent -V- WSU</a></h4>";
		}
	}
	?>
	<h5 class='event time <?php echo $awaystat; ?>'>
		<a href="<?php echo $_product->getProductUrl() ?>" title="<?=$eventName?>">
			<?php echo strftime("%a %e, %b %Y",strtotime($eventStart)); ?>
		</a>
	</h5>
	<?php               
	$cdate = strtotime($eventStart);
	$today = time();
	$tillevent = $cdate - $today;
	if ($tillevent < 0) { $tillevent = 0; }
	if($_product->isSaleable()){
		echo "<h6 class='event status comming'><a href='".$_product->getProductUrl()."' title='".$eventName."'>There are ". floor($tillevent/60/60/24)." days left</a></h6>";
	}else{
		echo "<h6 class='event status soldout'>Sold OUT!!</h6>";
	}

}