<?php 
$_helper = $this->helper('catalog/output'); 
$_product = $this->getProduct();

$RegistrationClosesDate = str_replace(' 00:00:00','',$_product->getRegistrationClosesDate());

$RegistrationClosesTime = $_product->getRegistrationClosesDate();
if( $RegistrationClosesTime == "" || $RegistrationClosesTime == "00:00:00" ){
$RegistrationClosesTime = '23:59:00';
}
$current_time = date("Y-m-d H:i:s");
$hasRegCloseDate = true;
$showItem=true;
$reg_deadline = $RegistrationClosesDate . ' ' . $RegistrationClosesTime;
if($RegistrationClosesDate =="" || strtotime($current_time) < strtotime($reg_deadline)){
	if($RegistrationClosesDate==""){
		$hasRegCloseDate = false;
	}
}else{
	$showItem=false;
	if(Mage::helper('wsu_networksecurities')->adminInFrontend()){
		$showItem=true;
	}
}

$FoodOptions = $_product->getFoodOptions();
$RequestSeating=$_product->getRequestSeating();
$HasAccessValidation = $_product->getHasAccessValidation();
$AccessCode = $_product->getAccessCode();
$Location = $_product->getLocation();


//this would be a block with in the event ext
$eventStart = Mage::getModel('core/date')->timestamp($_product->getEventStartDateTime());
$eventEnd = Mage::getModel('core/date')->timestamp($_product->getEventEndDateTime());


$relative_starttime = $_product->getRelativeStarttime();
$relative_endtime = $_product->getRelativeEndtime();



$eventStart_date = date('l, F jS, Y',$eventStart);
$eventEnd_date = date('l, F jS, Y',$eventEnd);

$eventStart_time = date('g:i a',$eventStart);
$eventEnd_time = date('g:i a',$eventEnd);		

$dateStr="";
$timeStr="";

if($eventStart_date==$eventEnd_date){
	$dateStr="<b>Date:</b> <i>$eventStart_date</i><br/>";

	$timeStr= ($relative_starttime!="") ? $relative_starttime : $eventStart_time;
	if($eventStart_time!=$eventEnd_time){
		$timeStr .= " to ";
		$timeStr .= ($relative_endtime!="") ? $relative_endtime : $eventEnd_time;
	}
	$timeStr= "<b>Time:</b> <i>$timeStr</i><br/>";
	$dateTimeHtml=$dateStr.$timeStr;
}
if($eventStart_date!=$eventEnd_date){
	$dateStr="<b>Date:</b> <i>$eventStart_date</i><br/>";
	$timeStr= ($relative_starttime!="") ? $relative_starttime : $eventStart_time;

	$timeStr= "<b>Time:</b> <i>$timeStr</i><br/>";
	$dateTimeHtml=$dateStr.$timeStr;

	$dateStr="<b>Date:</b> <i>$eventEnd_date</i><br/>";
	$timeStr= ($relative_endtime!="") ? $relative_endtime : $eventEnd_time;

	$timeStr= "<b>Time:</b> <i>$timeStr</i><br/>";

	$dateTimeHtml=$dateTimeHtml.$dateStr.$timeStr;
}


?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-shop">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                <h2><?php echo strftime("%A %e, %B %Y",strtotime($_product->getEventStartDate())); ?></h2>
				<?php               
                    $cdate = strtotime($_product->getEventStartDate());
                    $today = time();
                    $tillevent = $cdate - $today;
                    if ($tillevent < 0) { $tillevent = 0; }
                    echo "There are ". floor($tillevent/60/60/24)." days remaining";
                ?>
            </div>

            <?php if ($this->canEmailToFriend()): ?>
                <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
            <?php endif; ?>

            <?php //echo $this->getReviewsSummaryHtml($_product, false, true)?>
            <?php echo $this->getChildHtml('alert_urls') ?>
            <?php echo $this->getChildHtml('product_type_data') ?>
            <?php echo $this->getTierPriceHtml() ?>
            <?php echo $this->getChildHtml('extrahint') ?>
			
            
            <?php if ($tillevent==0):?>
            	<h3>Event tickets are no longer for sale</h3>
            <?php else: ?>
				<?php if (!$this->hasOptions()):?>
                <?php $qtyStock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty();
					echo sprintf("Currently there are %d tickets left",$qtyStock);
				 ?>
				 
					<?php if($HasAccessValidation): ?>
						<div class="validation_overlay">
							<div class="access_form">Enter Access Code<br/>
								<input type="text" class="full" data-valid="<?=$AccessCode?>"/>
							</div>
						</div>
					<?php endif; ?>
				 
				 
                    <div class="add-to-box <?=($HasAccessValidation?"needs_validation":"")?>">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                            <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                <span class="or"><?php echo $this->__('OR') ?></span>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php //echo $this->getChildHtml('addto') ?>
                    </div>
                <?php endif; ?>
			<?php endif; ?>
            <?php if ($_product->getShortDescription()):?>
                <div class="short-description">
                    <h2><?php echo $this->__('Quick Overview') ?></h2>
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                </div>
            <?php endif;?>

            <?php echo $this->getChildHtml('other');?>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>

        </div>

        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>

        <div class="clearer"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
    </form>
    
    <?php /*
		//@todo
		Look to the js controller script for the 
		var productAddToCartForm = new VarienForm('product_addtocart_form');
		it shouldbn't be in line.
	*/ ?>
    </div>

    <div class="product-collateral">
        <?php echo $this->getChildHtml('info_tabs') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
    </div>
</div>
