<?php 
$_helper = $this->helper('catalog/output'); 
$_product = $this->getProduct();

$RegistrationClosesDate = str_replace(' 00:00:00','',$_product->getRegistrationClosesDate());

$RegistrationClosesTime = $_product->getRegistrationClosesDate();
if( $RegistrationClosesTime == "" || $RegistrationClosesTime == "00:00:00" ){
$RegistrationClosesTime = '23:59:00';
}
$current_time = date("Y-m-d H:i:s");
$hasRegCloseDate = true;
$showItem=true;
$reg_deadline = $RegistrationClosesDate . ' ' . $RegistrationClosesTime;
if($RegistrationClosesDate =="" || strtotime($current_time) < strtotime($reg_deadline)){
	if($RegistrationClosesDate==""){
		$hasRegCloseDate = false;
	}
}else{
	$showItem=false;
	if(Mage::helper('wsu_networksecurities')->adminInFrontend()){
		$showItem=true;
	}
}

$food_options = $_product->getFoodOptions();
$request_seating=$_product->getRequestSeating();
$has_access_validation = $_product->getHasAccessValidation();
$access_code = $_product->getAccessCode();
$Location = $_product->getLocation();
$event_start_date = $_product->getEventStartDate();
$event_start_time = $_product->getEventStartTime();
$event_end_date = $_product->getEventEndDate();
$event_end_time = $_product->getEventEndTime();
$registration_closes_date = $_product->getRegistrationClosesDate();
$registration_closes_time = $_product->getRegistrationClosedTime();


$location_name = $_product->getLocationName();
$location_street = $_product->getLocationStreet();
$location_city = $_product->getLocationCity();
$location_state = $_product->getLocationState();
$location_zip = $_product->getLocationZip();
$location_lat = $_product->getLocationLat();
$location_long = $_product->getLocationLong();
$location_url = $_product->getLocationUrl();
$location_note = "";


$custom_accommodation_response = $_product->getCustomAccommodationResponse();
$has_sales_limit = $_product->getHasSalesLimit();
$collect_guest_info = $_product->getCollectGuestInfo();

//this would be a block with in the event ext
$eventStart = Mage::getModel('core/date')->timestamp($_product->getEventStartDateTime());
$eventEnd = Mage::getModel('core/date')->timestamp($_product->getEventEndDateTime());


$relative_starttime = $_product->getRelativeStarttime();
$relative_endtime = $_product->getRelativeEndtime();



$eventStart_date = date('l, F jS, Y',$eventStart);
$eventEnd_date = date('l, F jS, Y',$eventEnd);

$eventStart_time = date('g:i a',$eventStart);
$eventEnd_time = date('g:i a',$eventEnd);		

$dateStr="";
$timeStr="";

if($eventStart_date==$eventEnd_date){
	$dateStr="<b>Date:</b> <i>$eventStart_date</i><br/>";

	$timeStr= ($relative_starttime!="") ? $relative_starttime : $eventStart_time;
	if($eventStart_time!=$eventEnd_time){
		$timeStr .= " to ";
		$timeStr .= ($relative_endtime!="") ? $relative_endtime : $eventEnd_time;
	}
	$timeStr= "<b>Time:</b> <i>$timeStr</i><br/>";
	$dateTimeHtml=$dateStr.$timeStr;
}
if($eventStart_date!=$eventEnd_date){
	$dateStr="<b>Date:</b> <i>$eventStart_date</i><br/>";
	$timeStr= ($relative_starttime!="") ? $relative_starttime : $eventStart_time;

	$timeStr= "<b>Time:</b> <i>$timeStr</i><br/>";
	$dateTimeHtml=$dateStr.$timeStr;

	$dateStr="<b>Date:</b> <i>$eventEnd_date</i><br/>";
	$timeStr= ($relative_endtime!="") ? $relative_endtime : $eventEnd_time;

	$timeStr= "<b>Time:</b> <i>$timeStr</i><br/>";

	$dateTimeHtml=$dateTimeHtml.$dateStr.$timeStr;
}



$theme = $this->helper('wsu_themecontrol');
$template = $this->helper('wsu_themecontrol/template');


$row_type				= $theme->getCfgLayout('product_view/row_type');
$padding				= $theme->getCfgLayout('product_view/padding');
$padding_flanks			= $theme->getCfgLayout('product_view/padding_flanks');
$padding_ends			= $theme->getCfgLayout('product_view/padding_ends');

?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
	<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?> class="row <?=$row_type?> <?=$padding?>  <?=$padding_flanks?>  <?=$padding_ends?>">
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-shop column two">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                <h2><?php echo strftime("%A %e, %B %Y",strtotime($_product->getEventStartDate())); ?></h2>
				<?php               
                    $cdate = strtotime($_product->getEventStartDate());
                    $today = time();
                    $tillevent = $cdate - $today;
                    if ($tillevent < 0) { $tillevent = 0; }
                    echo "There are ". floor($tillevent/60/60/24)." days remaining";
                ?>
            </div>

            <?php if ($this->canEmailToFriend()): ?>
                <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
            <?php endif; ?>

            <?php //echo $this->getReviewsSummaryHtml($_product, false, true)?>
            <?php echo $this->getChildHtml('alert_urls') ?>
            <?php echo $this->getChildHtml('product_type_data') ?>
            <?php echo $this->getTierPriceHtml() ?>
            <?php echo $this->getChildHtml('extrahint') ?>
			
            
            <?php if ($tillevent==0):?>
            	<h3>Event tickets are no longer for sale</h3>
            <?php else: ?>
				<?php if (!$this->hasOptions()):?>
                <?php $qtyStock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty();
					echo sprintf("Currently there are %d tickets left",$qtyStock);
				 ?>
				 
					<?php if($has_access_validation): ?>
						<div class="validation_overlay">
							<div class="access_form">Enter Access Code<br/>
								<input type="text" class="full" data-valid="<?=$access_code?>"/>
							</div>
						</div>
					<?php endif; ?>
				 
				 
                    <div class="add-to-box <?=($has_access_validation?"needs_validation":"")?>">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                            <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                <span class="or"><?php echo $this->__('OR') ?></span>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php //echo $this->getChildHtml('addto') ?>
                    </div>
                <?php endif; ?>
			<?php endif; ?>
            <?php if ($_product->getDescription()):?>
                <div class="description">
                    <h2><?php echo $this->__('Overview') ?></h2>
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?></div>
                </div>
            <?php endif;?>

            <?php echo $this->getChildHtml('other');?>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>
			
			<?php if ( !empty($location_name) ):?>
				<h3><?=$location_name?></h3>
			<?php endif;?>
			
			<?php if ( !empty($location_street) ):?>
				<h4>Directions</h4>
				<?=$location_street?><br/>
				<?=$location_city?>, <?=$location_state?> <?=$location_zip?><br/>
				
			<?php endif;?>

			
			<?php if ( !empty($location_lat) && !empty($location_long) ):?>
			<script type="text/javascript">
				(function($){
					$(function() {
						var map = $('#WSU_MAPS_NS');
						map.on('wsu_maps:loaded_options',function(e,map_op){
							<?php if( !empty($location_lat) && !empty($location_long) ):?>
								$.wsu_maps.state.fit_to_bound=false;
							<?php endif; ?>
							return {<?= ( !empty($location_lat) && !empty($location_long) )? "'center': '".$location_lat.",".$location_long."'" : ''?> , 'zoom':15 };
						});
						map.on('wsu_maps:completed',function(){
							$.wsu_maps.markers.make_Marker(1,1,{
								"position":{ "latitude":"<?=$location_lat?>", "longitude":"<?=$location_long?>" },
								"labels":{ "title":"<?=$location_name?>" },
								"content":"<?=$location_note?>",
								"metadata":[{}],
								"shapes":[{}]
							 });
						});
					});
				})(jQuery);
			</script>
			<script type="text/javascript" src="https://beta.maps.wsu.edu/embed/store-event-location-tool"></script>
			<?php endif;?>
        </div>

        <div class="product-img-box column one">
            <?php echo $this->getChildHtml('media') ?>
        </div>

        <div class="clearer"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
    </form>
    
    <?php /*
		//@todo
		Look to the js controller script for the 
		var productAddToCartForm = new VarienForm('product_addtocart_form');
		it shouldbn't be in line.
	*/ ?>
    </div>

    <div class="product-collateral row padding narrow">
		<div class="column">
			<?php echo $this->getChildHtml('info_tabs') ?>
			<?php echo $this->getChildHtml('product_additional_data') ?>
		</div>
    </div>
</div>
<script type="text/javascript">
	//<![CDATA[
		var productAddToCartForm = new VarienForm('product_addtocart_form');
		productAddToCartForm.submit = function(button, url) {
			if (this.validator.validate()) {
				var form = this.form;
				var oldUrl = form.action;

				if (url) {
				   form.action = url;
				}
				var e = null;
				try {
					this.form.submit();
				} catch (e) {
				}
				this.form.action = oldUrl;
				if (e) {
					throw e;
				}

				if (button && button != 'undefined') {
					button.disabled = true;
				}
			}
		}.bind(productAddToCartForm);

		productAddToCartForm.submitLight = function(button, url){
			if(this.validator) {
				var nv = Validation.methods;
				delete Validation.methods['required-entry'];
				delete Validation.methods['validate-one-required'];
				delete Validation.methods['validate-one-required-by-name'];
				if (this.validator.validate()) {
					if (url) {
						this.form.action = url;
					}
					this.form.submit();
				}
				Object.extend(Validation.methods, nv);
			}
		}.bind(productAddToCartForm);
	//]]>
	</script>