<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Sales constrants</h4>
		<div class="form-buttons"><!--<button title="Create New Attribute" class="scalable add" id="create_attribute_252" onclick="create_attribute_252JsObject.create();" type="button"><span><span><span>Create New Attribute</span></span></span></button><script type="text/javascript">var create_attribute_252JsObject=new Product.Attributes('create_attribute_252');create_attribute_252JsObject.setConfig({"tab_id":"group_252","group_id":"252","store_id":0,"attribute_set_id":"67","type_id":"simple","product_id":"171","url":"http:\/\/store.wsu.edu\/index.php\/admin\/catalog_product_attribute\/new\/group\/252\/tab\/group_252\/store\/0\/product\/171\/set\/67\/type\/simple\/popup\/1\/key\/2bbbb4ce18231281f2a8b68472685ddc\/"});</script>--></div>
	</div>
	<div class="fieldset fieldset-wide" id="group_fields252">
		<div class="hor-scroll">
			<table class="form-list" cellspacing="0">
				<tbody>
					<tr>
						<td class="label"><label for="has_access_validation">Needs Access Validation</label></td>
						<td class="value"><select name="product[has_access_validation]" class=" select" id="has_access_validation">
								<option selected="selected" value="">No</option>
								<option value="">Yes</option>
							</select></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="access_code">Access Code</label></td>
						<td class="value"><input name="product[access_code]" class=" input-text" id="access_code" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="registration_closed">When should the registration end? (will be a 11:59pm of this date))</label></td>
						<td class="value"><input name="product[registration_closed]" class=" input-text" id="registration_closed" style="width: 110px !important;" type="text" value="">
							<i class="fa fa-calendar" id="registration_closed_trig" style=" cursor:pointer;"></i> 
							<script type="text/javascript">Calendar.setup({inputField:"registration_closed",ifFormat:"%m/%e/%Y",showsTime:false,button:"registration_closed_trig",align:"Bl",singleClick:true});</script></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
