<?php 
$model = Mage::helper('wsu_eventtickets')->getEventticketsItemInstance();
$su = Mage::helper('storeutilities/utilities');
?><div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form-constrants fieldset-legend">Sales constrants</h4>
		<div class="form-buttons"><!--<button title="Create New Attribute" class="scalable add" id="create_attribute_252" onclick="create_attribute_252JsObject.create();" type="button"><span><span><span>Create New Attribute</span></span></span></button><script type="text/javascript">var create_attribute_252JsObject=new Product.Attributes('create_attribute_252');create_attribute_252JsObject.setConfig({"tab_id":"group_252","group_id":"252","store_id":0,"attribute_set_id":"67","type_id":"simple","product_id":"171","url":"http:\/\/store.wsu.edu\/index.php\/admin\/catalog_product_attribute\/new\/group\/252\/tab\/group_252\/store\/0\/product\/171\/set\/67\/type\/simple\/popup\/1\/key\/2bbbb4ce18231281f2a8b68472685ddc\/"});</script>--></div>
	</div>
	<div class="fieldset fieldset-wide" id="group_fields252">
		<div class="hor-scroll">
			<table class="form-list" cellspacing="0">
				<tbody>
					<tr>
						<td class="label"><label for="registration_closes_date">Registration end</label></td>
						<td class="value">
							<label for="location">Date
							<input name="product[registration_closes_date]" class=" input-text" id="registration_closes_date" style="width: 110px !important;" type="text" value="<?=$model->getRegistrationClosesDate()?>">
							<i class="fa fa-calendar" id="registration_closed_trig" style=" cursor:pointer;"></i> 
							<script type="text/javascript">Calendar.setup({inputField:"registration_closes_date",ifFormat:"%m/%e/%Y",showsTime:false,button:"registration_closed_trig",align:"Bl",singleClick:true});</script>
							</label>
							<br/>
							
							<label for="location">Time
							<input name="product[registration_closes_time]" class=" input-text" id="registration_closes_time" style="width: 110px !important;" type="text" value="<?=$model->getRegistrationClosesTime()?>">
							<i class="fa fa-clock-o" id="registration_closed_time_trig" style=" cursor:pointer;"></i> 
							<script type="text/javascript">Calendar.setup({ inputField:"registration_closes_time", ifFormat:"%H:%M:%S", time24:"24", showsTime:true, button:"registration_closed_time_trig", align:"Bl", singleClick:true, weekNumbers:false, });</script>
							</label>
							
							</td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="has_access_validation">Event access validation</label></td>
						<td class="value">
							<select name="product[has_access_validation]" class=" select switch" data-type="has_access_validation" id="has_access_validation" style="width: 110px !important;">
								<option <?=$su->selected('0',$model->getHasAccessValidation())?> value="0">No</option>
								<option <?=$su->selected('1',$model->getHasAccessValidation())?> value="1">Yes</option>
							</select>
							<label for="access_code" class="has_access_validation"  <?=($model->getHasAccessValidation()!='1'?'style="display:none"':'')?>>Access Code: <input name="product[access_code]" class=" input-text" id="access_code" type="text" value="<?=$model->getAccessCode()?>" style="width: 110px !important;"></label>
						</td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="has_sales_limit">Limit sales quantity</label></td>
						<td class="value">
							<select name="product[has_sales_limit]" class=" select switch" data-type="has_sales_limit" id="has_sales_limit" style="width: 110px !important;">
								<option <?=$su->selected('0',$model->getHasSalesLimit())?> value="0">No</option>
								<option <?=$su->selected('1',$model->getHasSalesLimit())?> value="1">Yes</option>
							</select>
							<label for="sales_limit_amount" class="has_sales_limit"  <?=($model->getHasSalesLimit()!='1'?'style="display:none"':'')?>> to <input name="product[sales_limit_amount]" class=" input-text" id="sales_limit_amount" type="text" value="<?=$model->getSalesLimitAmount()?>" style="width: 110px !important;"></label>
						</td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
