<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">General info</h4>
		<div class="form-buttons"><!--<button title="Create New Attribute" class="scalable add" id="create_attribute_252" onclick="create_attribute_252JsObject.create();" type="button"><span><span><span>Create New Attribute</span></span></span></button><script type="text/javascript">var create_attribute_252JsObject=new Product.Attributes('create_attribute_252');create_attribute_252JsObject.setConfig({"tab_id":"group_252","group_id":"252","store_id":0,"attribute_set_id":"67","type_id":"simple","product_id":"171","url":"http:\/\/store.wsu.edu\/index.php\/admin\/catalog_product_attribute\/new\/group\/252\/tab\/group_252\/store\/0\/product\/171\/set\/67\/type\/simple\/popup\/1\/key\/2bbbb4ce18231281f2a8b68472685ddc\/"});</script>--></div>
	</div>
	<div class="fieldset fieldset-wide" id="group_fields252">
		<div class="hor-scroll">
			<table class="form-list" cellspacing="0">
				<tbody>
					<tr>
						<td class="label"><label for="event_start_date_time">Date &amp; Time</label></td>
						<td class="value"><input name="product[event_start_date_time]" class=" input-text" id="event_start_date_time" style="width: 50%;" type="text" value="">
							<i class="fa fa-calendar"  id="event_start_date_time_trig" style=" cursor:pointer;"></i>
							<script type="text/javascript">Calendar.setup({inputField:"event_start_date_time",ifFormat:"%m/%e/%Y %I:%M %p",showsTime:true,button:"event_start_date_time_trig",align:"Bl",singleClick:true});</script></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="event_end_date_time">End Date &amp; Time</label></td>
						<td class="value"><input name="product[event_end_date_time]" class=" input-text" id="event_end_date_time" style="width: 50%;" type="text" value="">
							<i class="fa fa-calendar"  id="event_end_date_time_trig" style=" cursor:pointer;"></i>
							<script type="text/javascript">Calendar.setup({inputField:"event_end_date_time",ifFormat:"%m/%e/%Y %I:%M %p",showsTime:true,button:"event_end_date_time_trig",align:"Bl",singleClick:true});</script></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_name">Location</label></td>
						<td class="value"><input name="product[location_name]" class=" input-text" id="location_name" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_street">Street Address</label></td>
						<td class="value"><input name="product[location_street]" class=" input-text" id="location_street" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_city">City</label></td>
						<td class="value"><input name="product[location_city]" class=" input-text" id="location_city" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_name">State</label></td>
						<td class="value"><input name="product[location_state]" class=" input-text" id="location_state" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_zip">Zip</label></td>
						<td class="value"><input name="product[location_zip]" class=" input-text" id="location_zip" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location">Location</label></td>
						<td class="value">
						<label for="location">Location Lat<input name="product[location_lat]" class=" input-text" id="location_lat" type="text" value=""></label>
						<label for="location">Location Long<input name="product[location_long]" class=" input-text" id="location_lat" type="text" value=""></label>
						<script type="text/javascript" src="https://beta.maps.wsu.edu/embed/store-event-location-tool"></script>
						</td>
						<td></td>
					</tr>
					

					
					<tr>
						<td class="label"><label for="guest_limit">Guest Limit</label></td>
						<td class="value"><select name="product[guest_limit]" class=" select" id="guest_limit">
								<option value=""></option>
								<option selected="selected" value="">unlimited</option>
								<option value="">1</option>
								<option value="">2</option>
								<option value="">3</option>
								<option value="">4</option>
								<option value="">5</option>
								<option value="">6</option>
								<option value="">7</option>
								<option value="">8</option>
								<option value="">9</option>
								<option value="">10</option>
							</select></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="allow_guests">Allow Guests</label></td>
						<td class="value"><select name="product[allow_guests]" class=" select" id="allow_guests">
								<option value="">No</option>
								<option selected="selected" value="">Yes</option>
							</select></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="food_options">Has Food Options</label></td>
						<td class="value"><select name="product[food_options]" class=" select" id="food_options">
								<option selected="selected" value="">No</option>
								<option value="">Yes</option>
							</select></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="relative_starttime">Relative Event Time</label></td>
						<td class="value"><input name="product[relative_starttime]" class=" input-text" id="relative_starttime" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="relative_endtime">Relative Event End Time</label></td>
						<td class="value"><input name="product[relative_endtime]" class=" input-text" id="relative_endtime" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="request_seating">Can request seating</label></td>
						<td class="value"><select name="product[request_seating]" class=" select" id="request_seating">
								<option selected="selected" value="">No</option>
								<option value="">Yes</option>
							</select></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="guest_info">Collect Guest info</label></td>
						<td class="value"><select name="product[guest_info]" class=" select" id="guest_info">
								<option value="">No</option>
								<option selected="selected" value="">Yes</option>
							</select></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="menu_age_price_range">Is there an age range for the menu</label></td>
						<td class="value"><select name="product[menu_age_price_range]" class=" select" id="menu_age_price_range">
								<option value="">No</option>
								<option selected="selected" value="">Yes</option>
							</select></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
