<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">General info</h4>
		<div class="form-buttons"></div>
	</div>
	<div class="fieldset fieldset-wide" id="group_fields252">
		<div class="hor-scroll">
			<table class="form-list" cellspacing="0">
				<tbody>
					<tr>
						<td class="label"><label for="allow_guests">Allow Guests</label></td>
						<td class="value"><select name="product[allow_guests]" class=" select" id="allow_guests">
								<option value="">No</option>s
								<option selected="selected" value="">Yes</option>
							</select></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="guest_info">Collect Guest info</label></td>
						<td class="value"><select name="product[guest_info]" class=" select" id="guest_info">
								<option value="">No</option>
								<option selected="selected" value="">Yes</option>
							</select></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="guest_limit">Guest Limit</label></td>
						<td class="value"><select name="product[guest_limit]" class=" select" id="guest_limit">
								<option value=""></option>
								<option selected="selected" value="">unlimited</option>
								<option value="">1</option>
								<option value="">2</option>
								<option value="">3</option>
								<option value="">4</option>
								<option value="">5</option>
								<option value="">6</option>
								<option value="">7</option>
								<option value="">8</option>
								<option value="">9</option>
								<option value="">10</option>
							</select></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
