<?php
$model = Mage::helper('wsu_eventtickets')->getEventticketsItemInstance();
$su = Mage::helper('storeutilities/utilities');
$guest_allowed = $model->getAllowGuests();
?><div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form-guests fieldset-legend">Ticket guest options</h4>
		<div class="form-buttons"></div>
	</div>
	<div class="fieldset fieldset-wide" id="group_fields252">
		<div class="hor-scroll">
			<table class="form-list" cellspacing="0">
				<tbody>
					<tr>
						<td class="label"><label for="allow_guests">Allow Guests</label></td>
						<td class="value"><select name="product[allow_guests]" class=" select switch" data-type="allow_guests" id="allow_guests">
								<option <?=$su->selected('0',$guest_allowed)?> value="0">No</option>
								<option <?=$su->selected('1',$guest_allowed)?> value="1">Yes</option>
							</select></td>
						<td></td>
					</tr>
					<tr class="allow_guests" <?=($guest_allowed!='1'?'style="display:none"':'')?>>
						<td class="label"><label for="collect_guest_info">Collect Guest info</label></td>
						<td class="value"><select name="product[collect_guest_info]" class=" select" id="collect_guest_info">
								<option <?=$su->selected('0',$model->getCollectGuestInfo())?> value="0">No</option>
								<option <?=$su->selected('1',$model->getCollectGuestInfo())?> value="1">Yes</option>
							</select></td>
						<td></td>
					</tr>
					<tr class="allow_guests" <?=($guest_allowed!='1'?'style="display:none"':'')?>>
						<td class="label"><label for="guest_limit">Guest Limit</label></td>
						<td class="value"><select name="product[guest_limit]" class=" select" id="guest_limit">
								<option <?=$su->selected('',$model->getCollectGuestInfo())?> value=""></option>
								<option <?=$su->selected('unlimited',$model->getCollectGuestInfo())?> value="unlimited">unlimited</option>
								<?php for( $i=1; $i<16; $i++ ): ?>
									<option <?=$su->selected($i,$model->getCollectGuestInfo())?>><?=$i?></option>
								<?php endfor; ?>
							</select></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
