<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form-guests fieldset-legend">Purchase Information</h4>
		<div class="form-buttons"></div>
	</div>
	<div class="fieldset fieldset-wide" id="group_fields252">
		<div class="hor-scroll">
			<table class="form-list" cellspacing="0">
				<tbody>
					<tr>
						<td class="label"><label for="guest_limit">labels?</label></td>
						<td class="value">Fields?</td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
