<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form-event-location fieldset-legend">Event Location</h4>
		<div class="form-buttons"></div>
	</div>
	<div class="fieldset fieldset-wide" id="group_fields252">
		<div class="hor-scroll">
			<table class="form-list" cellspacing="0">
				<tbody>
					<tr>
						<td class="label"><label for="location_name">Location</label></td>
						<td class="value"><input name="product[location_name]" class=" input-text" id="location_name" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_street">Street Address</label></td>
						<td class="value"><input name="product[location_street]" class=" input-text" id="location_street" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_city">City</label></td>
						<td class="value"><input name="product[location_city]" class=" input-text" id="location_city" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_name">State</label></td>
						<td class="value"><input name="product[location_state]" class=" input-text" id="location_state" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_zip">Zip</label></td>
						<td class="value"><input name="product[location_zip]" class=" input-text" id="location_zip" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location">Location</label></td>
						<td class="value">
						<label for="location">latitude<input name="product[location_lat]" class=" input-text" id="location_lat" type="text" value=""></label>
						<br/>
						<label for="location">longitude<input name="product[location_long]" class=" input-text" id="location_lat" type="text" value=""></label>
						<script type="text/javascript" src="https://beta.maps.wsu.edu/embed/store-event-location-tool?dyno=true&?debug=true"></script>
						
						<script type="text/javascript">
							(function($){
								$(function() {
									var map = $('#WSU_MAPS_NS');
									map.on('wsu_maps:completed',function(){
									
										$.wsu_maps.markers.make_Marker(1,1,{
											"position":{ "latitude":"47.041569", "longitude":"-122.892262" },
											"labels":{ "title":"", "prime_abbrev":"", "other_names":"" },
										 });
										 
										 
										map.on('wsu_maps:marker_added',function(e,marker){
											console.log('set to drag');
											marker.setDraggable(true);
										});
										 
										map.on('wsu_maps:marker_dragend',function(e,marker){
											console.log('drangin');
											var placePos = marker.getPosition();
											var lat = placePos.lat();
											var lng = placePos.lng();
											console.log(lat );
											console.log(lng );
											$('#location_lat').val(lat);
											$('#location_long').val(lng);
										});
									});	
								});
							})(jQuery);
						</script>
		
						</td>
						<td></td>
					</tr>
					
				</tbody>
			</table>
		</div>
	</div>
</div>
