<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">General info</h4>
		<div class="form-buttons"><!--<button title="Create New Attribute" class="scalable add" id="create_attribute_252" onclick="create_attribute_252JsObject.create();" type="button"><span><span><span>Create New Attribute</span></span></span></button><script type="text/javascript">var create_attribute_252JsObject=new Product.Attributes('create_attribute_252');create_attribute_252JsObject.setConfig({"tab_id":"group_252","group_id":"252","store_id":0,"attribute_set_id":"67","type_id":"simple","product_id":"171","url":"http:\/\/store.wsu.edu\/index.php\/admin\/catalog_product_attribute\/new\/group\/252\/tab\/group_252\/store\/0\/product\/171\/set\/67\/type\/simple\/popup\/1\/key\/2bbbb4ce18231281f2a8b68472685ddc\/"});</script>--></div>
	</div>
	<div class="fieldset fieldset-wide" id="group_fields252">
		<div class="hor-scroll">
			<table class="form-list" cellspacing="0">
				<tbody>
					<tr>
						<td class="label"><label for="location_name">Location</label></td>
						<td class="value"><input name="product[location_name]" class=" input-text" id="location_name" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_street">Street Address</label></td>
						<td class="value"><input name="product[location_street]" class=" input-text" id="location_street" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_city">City</label></td>
						<td class="value"><input name="product[location_city]" class=" input-text" id="location_city" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_name">State</label></td>
						<td class="value"><input name="product[location_state]" class=" input-text" id="location_state" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_zip">Zip</label></td>
						<td class="value"><input name="product[location_zip]" class=" input-text" id="location_zip" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location">Location</label></td>
						<td class="value">
						<label for="location">Location Lat<input name="product[location_lat]" class=" input-text" id="location_lat" type="text" value=""></label>
						<br/>
						<label for="location">Location Long<input name="product[location_long]" class=" input-text" id="location_lat" type="text" value=""></label>
						<script type="text/javascript" src="https://beta.maps.wsu.edu/embed/store-event-location-tool"></script>
						</td>
						<td></td>
					</tr>
					
				</tbody>
			</table>
		</div>
	</div>
</div>
