<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form-event-location fieldset-legend">Event Location</h4>
		<div class="form-buttons"></div>
	</div>
	<div class="fieldset fieldset-wide" id="group_fields252">
		<div class="hor-scroll">
			<table class="form-list" cellspacing="0">
				<tbody>
					<tr>
						<td class="label"><label for="location_name">Location Name</label></td>
						<td class="value"><input name="product[location_name]" class=" input-text" id="location_name" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_street">Street Address</label></td>
						<td class="value"><input name="product[location_street]" class=" input-text" id="location_street" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_city">City</label></td>
						<td class="value"><input name="product[location_city]" class=" input-text" id="location_city" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_name">State</label></td>
						<td class="value"><input name="product[location_state]" class=" input-text" id="location_state" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location_zip">Zip</label></td>
						<td class="value"><input name="product[location_zip]" class=" input-text" id="location_zip" type="text" value=""></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="location">Location</label></td>
						<td class="value">
						<label for="location">latitude<input name="product[location_lat]" class=" input-text" id="location_lat" type="text" value=""></label>
						<br/>
						<label for="location">longitude<input name="product[location_long]" class=" input-text" id="location_long" type="text" value=""></label>
						<script type="text/javascript" src="https://beta.maps.wsu.edu/embed/store-event-location-tool?dyno=true"></script>
						
						<script type="text/javascript">
							(function($){
								$(function() {
									var map = $('#WSU_MAPS_NS');
									var geocoder = null;
									map.on('wsu_maps:completed',function(){
										geocoder = new google.maps.Geocoder();
										$.wsu_maps.markers.make_Marker(1,1,{
											"position":{ "latitude":"46.725722661815745", "longitude":"-117.16131040741038" },
											"labels":{ "title":"", "prime_abbrev":"", "other_names":"" },
											"content":"test",
											"metadata":[{}],
											"shapes":[{}]
										 });
										 
										 
										
									});	
									map.on('wsu_maps:marker_added',function(e,marker){
										console.log('set to drag');
										console.log(marker);
										marker.setDraggable(true);
									});
									
									map.on('wsu_maps:marker_dragend',function(e,marker){
										console.log('drangin');
										var placePos = marker.getPosition();
										var lat = placePos.lat();
										var lng = placePos.lng();
										console.log(lat );
										console.log(lng );
										$('#location_lat').val(lat);
										$('#location_long').val(lng);
										
										var loca = new google.maps.LatLng(lat,lng);
										geocoder.geocode({'latLng':loca}, function(results, status) {
											if (status === google.maps.GeocoderStatus.OK) { 
												var arrAddress = results[0].address_components;
												
												var itemRoute='';
												var itemLocality='';
												var itemCountry='';
												var itemPc='';
												var itemState='';
												var itemSnumber='';
												//$('#place_address').val('');
												//$('#place_street').val('');			
												// iterate through address_component array
												$.each(arrAddress, function (i, address_component) {
													if (address_component.types[0] === "route"){//": route:"
														itemRoute = address_component.long_name;
													}
													if (address_component.types[0] === "locality"){//"town:"
														itemLocality = address_component.long_name;
													}
													if (address_component.types[0] === "country"){ //"country:"
														itemCountry = address_component.long_name;
													}
													if (address_component.types[0] === "postal_code"){ //"pc:"
														itemPc = address_component.long_name;
														
													}
													if (address_component.types[0] === "administrative_area_level_1"){ //"pc:"
														itemState = address_component.long_name;
													}
													if (address_component.types[0] === "street_number"){ //"street_number:"
														itemSnumber = address_component.long_name;
													}
													$('#location_zip').val(itemPc);
													$('#location_city').val(itemLocality);
													$('#location_state').val(itemState);
													$('#location_street').val(itemSnumber + ' ' + itemRoute);
													
												});
												if (results[1]) {
													//alert( results[1].formatted_address);
													//obj.val(itemSnumber);
												}
											} else {
												alert("Geocoder failed due to: " + status);
											}
										});
										
										
									});
								});
							})(jQuery);
						</script>
		
						</td>
						<td></td>
					</tr>
					
				</tbody>
			</table>
		</div>
	</div>
</div>
