<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form-guests fieldset-legend">Food options</h4>
		<div class="form-buttons"></div>
	</div>
	<div class="fieldset fieldset-wide" id="group_fields252">
		<div class="hor-scroll">
			<table class="form-list" cellspacing="0">
				<tbody>
					<tr>
						<td class="label"><label for="food_options">Has Food Options</label></td>
						<td class="value"><select name="product[food_options]" class=" select" id="food_options">
								<option selected="selected" value="">No</option>
								<option value="">Yes</option>
							</select></td>
						<td></td>
					</tr>
					<tr>
						<td class="label"><label for="menu_age_price_range">Is there an age range for the menu</label></td>
						<td class="value"><select name="product[menu_age_price_range]" class=" select" id="menu_age_price_range">
								<option value="">No</option>
								<option selected="selected" value="">Yes</option>
							</select></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form-guests fieldset-legend">Accommodations</h4>
		<div class="form-buttons"></div>
	</div>
	<div class="fieldset fieldset-wide" id="group_fields252">
		<div class="hor-scroll">
			<table class="form-list" cellspacing="0">
				<tbody>				
					<tr>
						<td class="label"><label for="request_seating">Can request seating</label></td>
						<td class="value"><select name="product[request_seating]" class=" select" id="request_seating">
								<option selected="selected" value="">No</option>
								<option value="">Yes</option>
							</select></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
