<?php
/* 
 * @category  Event Manager Module
 * @package   Wsu_eventTickets 
 * @author    Jeremy Bass <jeremy.bass@wsu.edu>
 * @license   MIT/GPL
 * @link N/A 
 */
?>
<?php $_eventticketsItem = $this->helper('wsu_eventtickets')->geteventTicketsItemInstance(); ?>
<div id="eventtickets_item_messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="page-title">
    <h1><?php echo $this->escapeHtml($_eventticketsItem->getTitle()) ?></h1>

    <div class="eventtickets_item_subtitle">
        <?php echo $this->formatDate($_eventticketsItem->getTimePublished(), Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM) ?> 
         <?php echo "<br/>Venue Details: ". $this->escapeHtml($_eventticketsItem->getVenue())?> 
		<?php echo "<br/>Entry Fee: ".Mage::helper('core')->currency($_eventticketsItem->getEntryFee()); ?>
    </div>
	
</div>

<div class="eventtickets_item_view">
    <?php if ($imageUrl = $this->getImageUrl($_eventticketsItem, 400)): ?>
       <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($_eventticketsItem->getTitle()) ?>" /></p>
    <?php endif; ?>
    <div class="eventtickets_item_content"><span style="font-size:14px;font-weight:bold">Event Details</span><br/><?php echo $_eventticketsItem->getDetails(); ?></div>
	 <div class="eventtickets_item_content"><span style="font-size:14px;font-weight:bold">Eligibility</span><br/><?php echo $_eventticketsItem->getEligibility(); ?></div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo Mage::helper('wsu_eventtickets')->__('Return to list') ?>
        </a>
    </div>
</div>
